// Аналогии для 1 класса: "А относится к Б, как В относится к ?"
// Формат карточки: пара-образец (from → to) + новый элемент (from2), нужно
// подобрать to2 по тому же правилу. 4 варианта ответа, один верный.
// Каждая аналогия перепроверена дважды на однозначность связи для 7–8 лет.

export interface Analogy {
  id: string;
  fromEmoji: string;
  fromWord: string;
  toEmoji: string;
  toWord: string;
  from2Emoji: string;
  from2Word: string;
  correctEmoji: string;
  correctWord: string;
  wrongOptions: { emoji: string; word: string }[];
  rule: string; // краткое описание правила связи, для проверки
}

export const ANALOGIES: Analogy[] = [
  {
    id: 'sobaka-buda',
    fromEmoji: '🐕',
    fromWord: 'Собака',
    toEmoji: '🏠',
    toWord: 'Будка',
    from2Emoji: '🐦',
    from2Word: 'Птица',
    correctEmoji: '🪺',
    correctWord: 'Гнездо',
    wrongOptions: [
      { emoji: '🦴', word: 'Кость' },
      { emoji: '🐟', word: 'Рыба' },
      { emoji: '🌳', word: 'Дерево' },
    ],
    rule: 'жилище животного',
  },
  {
    id: 'ryba-voda',
    fromEmoji: '🐟',
    fromWord: 'Рыба',
    toEmoji: '💧',
    toWord: 'Вода',
    from2Emoji: '🐦',
    from2Word: 'Птица',
    correctEmoji: '☁️',
    correctWord: 'Небо',
    wrongOptions: [
      { emoji: '🪺', word: 'Гнездо' },
      { emoji: '🌾', word: 'Зерно' },
      { emoji: '🌊', word: 'Море' },
    ],
    rule: 'среда обитания',
  },
  {
    id: 'koshka-kotenok',
    fromEmoji: '🐱',
    fromWord: 'Кошка',
    toEmoji: '🐈',
    toWord: 'Котёнок',
    from2Emoji: '🐕',
    from2Word: 'Собака',
    correctEmoji: '🐶',
    correctWord: 'Щенок',
    wrongOptions: [
      { emoji: '🦴', word: 'Кость' },
      { emoji: '🐄', word: 'Корова' },
      { emoji: '🏠', word: 'Будка' },
    ],
    rule: 'мама и детёныш',
  },
  {
    id: 'korova-moloko',
    fromEmoji: '🐄',
    fromWord: 'Корова',
    toEmoji: '🥛',
    toWord: 'Молоко',
    from2Emoji: '🐝',
    from2Word: 'Пчела',
    correctEmoji: '🍯',
    correctWord: 'Мёд',
    wrongOptions: [
      { emoji: '🌸', word: 'Цветок' },
      { emoji: '🐛', word: 'Гусеница' },
      { emoji: '🥚', word: 'Яйцо' },
    ],
    rule: 'кто что даёт (продукт)',
  },
  {
    id: 'den-noch',
    fromEmoji: '☀️',
    fromWord: 'День',
    toEmoji: '🌙',
    toWord: 'Ночь',
    from2Emoji: '🔥',
    from2Word: 'Горячий',
    correctEmoji: '🧊',
    correctWord: 'Холодный',
    wrongOptions: [
      { emoji: '💧', word: 'Мокрый' },
      { emoji: '🌡️', word: 'Тёплый' },
      { emoji: '⚡', word: 'Быстрый' },
    ],
    rule: 'противоположности',
  },
  {
    id: 'derevo-list',
    fromEmoji: '🌳',
    fromWord: 'Дерево',
    toEmoji: '🍃',
    toWord: 'Лист',
    from2Emoji: '🏠',
    from2Word: 'Дом',
    correctEmoji: '🧱',
    correctWord: 'Крыша',
    wrongOptions: [
      { emoji: '🚪', word: 'Дверь' },
      { emoji: '🪟', word: 'Окно' },
      { emoji: '🌲', word: 'Ветка' },
    ],
    rule: 'целое и часть',
  },
  {
    id: 'ptica-gnezdo-medved',
    fromEmoji: '🐦',
    fromWord: 'Птица',
    toEmoji: '🪺',
    toWord: 'Гнездо',
    from2Emoji: '🐻',
    from2Word: 'Медведь',
    correctEmoji: '🕳️',
    correctWord: 'Берлога',
    wrongOptions: [
      { emoji: '🍯', word: 'Мёд' },
      { emoji: '🐟', word: 'Рыба' },
      { emoji: '❄️', word: 'Снег' },
    ],
    rule: 'жилище животного',
  },
  {
    id: 'bolshoy-malenkiy',
    fromEmoji: '🐘',
    fromWord: 'Большой',
    toEmoji: '🐭',
    toWord: 'Маленький',
    from2Emoji: '🐇',
    from2Word: 'Быстрый',
    correctEmoji: '🐢',
    correctWord: 'Медленный',
    wrongOptions: [
      { emoji: '💪', word: 'Сильный' },
      { emoji: '🎨', word: 'Цветной' },
      { emoji: '🔊', word: 'Громкий' },
    ],
    rule: 'противоположности',
  },
  {
    id: 'uchenik-shkola',
    fromEmoji: '🧑‍🎓',
    fromWord: 'Ученик',
    toEmoji: '🏫',
    toWord: 'Школа',
    from2Emoji: '🤒',
    from2Word: 'Пациент',
    correctEmoji: '🏥',
    correctWord: 'Больница',
    wrongOptions: [
      { emoji: '💊', word: 'Лекарство' },
      { emoji: '👨‍⚕️', word: 'Врач' },
      { emoji: '📚', word: 'Книга' },
    ],
    rule: 'кто куда приходит по роли',
  },
  {
    id: 'kurica-cyplenok',
    fromEmoji: '🐔',
    fromWord: 'Курица',
    toEmoji: '🐣',
    toWord: 'Цыплёнок',
    from2Emoji: '🐖',
    from2Word: 'Свинья',
    correctEmoji: '🐷',
    correctWord: 'Поросёнок',
    wrongOptions: [
      { emoji: '🥛', word: 'Молоко' },
      { emoji: '🌾', word: 'Трава' },
      { emoji: '🐐', word: 'Коза' },
    ],
    rule: 'мама и детёныш',
  },
  {
    id: 'hudozhnik-kartina',
    fromEmoji: '🧑‍🎨',
    fromWord: 'Художник',
    toEmoji: '🖼️',
    toWord: 'Картина',
    from2Emoji: '👨‍🍳',
    from2Word: 'Повар',
    correctEmoji: '🍲',
    correctWord: 'Суп',
    wrongOptions: [
      { emoji: '🔪', word: 'Нож' },
      { emoji: '✏️', word: 'Карандаш' },
      { emoji: '🍽️', word: 'Тарелка' },
    ],
    rule: 'мастер и то, что он создаёт',
  },
  {
    id: 'zima-sneg',
    fromEmoji: '❄️',
    fromWord: 'Зима',
    toEmoji: '⛄',
    toWord: 'Снеговик',
    from2Emoji: '🌞',
    from2Word: 'Лето',
    correctEmoji: '🏖️',
    correctWord: 'Пляж',
    wrongOptions: [
      { emoji: '🧣', word: 'Шарф' },
      { emoji: '🎿', word: 'Лыжи' },
      { emoji: '🧤', word: 'Варежки' },
    ],
    rule: 'время года и то, что с ним связано',
  },
  {
    id: 'glaza-vidyat',
    fromEmoji: '👀',
    fromWord: 'Глаза',
    toEmoji: '👁️‍🗨️',
    toWord: 'Видят',
    from2Emoji: '👂',
    from2Word: 'Уши',
    correctEmoji: '🔊',
    correctWord: 'Слышат',
    wrongOptions: [
      { emoji: '👃', word: 'Нюхают' },
      { emoji: '👅', word: 'Пробуют' },
      { emoji: '✋', word: 'Трогают' },
    ],
    rule: 'орган и его функция',
  },
  {
    id: 'noga-botinok',
    fromEmoji: '🦶',
    fromWord: 'Нога',
    toEmoji: '👟',
    toWord: 'Ботинок',
    from2Emoji: '✋',
    from2Word: 'Рука',
    correctEmoji: '🧤',
    correctWord: 'Перчатка',
    wrongOptions: [
      { emoji: '🧦', word: 'Носок' },
      { emoji: '👕', word: 'Футболка' },
      { emoji: '🎩', word: 'Шляпа' },
    ],
    rule: 'часть тела и то, что на неё надевают',
  },
];
