// 52 «цветные» темы, свёрстанные вручную в коде (app/{segment}/{subject}/{slug}/page.tsx).
// Они НЕ хранятся в БД и правятся только в коде (мной). В админке показываются
// как read-only с пометкой «код» — чтобы ничего не выглядело фейковым.
export const CODE_TOPIC_ROUTES: string[] = [
  // 4–5 лет
  '/4-5-let/matematika/schet-do-5',
  '/4-5-let/matematika/schet-do-10',
  '/4-5-let/matematika/figury',
  '/4-5-let/matematika/tsveta',
  '/4-5-let/razvitie/zvuki',
  '/4-5-let/razvitie/slova',
  '/4-5-let/razvitie/pereskaz-po-kartinkam',
  '/4-5-let/gramota/bukvy',
  '/4-5-let/gramota/slogov',
  '/4-5-let/gramota/shtrikhovka-i-graficheskie-diktanty',
  '/4-5-let/logika/naydi-lishnee',
  '/4-5-let/logika/sravnenie-predmetov',
  '/4-5-let/logika/zagadki',
  '/4-5-let/okruzhayushchiy/vremena-goda',
  '/4-5-let/okruzhayushchiy/domashnie-i-dikie-zhivotnye',
  // 6–7 лет
  '/6-7-let/matematika/schet-do-20',
  '/6-7-let/matematika/slozhenie',
  '/6-7-let/matematika/vychitanie',
  '/6-7-let/matematika/vremya',
  '/6-7-let/matematika/sostav-chisla',
  '/6-7-let/razvitie/dialogi',
  '/6-7-let/razvitie/rasskazy',
  '/6-7-let/razvitie/pereskaz-po-kartinkam',
  '/6-7-let/gramota/chtenie',
  '/6-7-let/gramota/pisanie',
  '/6-7-let/gramota/shtrikhovka-i-graficheskie-diktanty',
  '/6-7-let/logika/zakonomernosti',
  '/6-7-let/logika/zagadki',
  '/6-7-let/okruzhayushchiy/prirodnye-yavleniya',
  '/6-7-let/okruzhayushchiy/telo-cheloveka',
  // 1 класс
  '/1-klass/matematika/slozhenie-5-10',
  '/1-klass/matematika/vychitanie-5-10',
  '/1-klass/matematika/zadachi',
  '/1-klass/matematika/sostav-chisla',
  '/1-klass/russkiy/pisanie',
  '/1-klass/russkiy/punktuaciya',
  '/1-klass/russkiy/glasnye-i-soglasnye',
  '/1-klass/russkiy/udarenie',
  '/1-klass/russkiy/shtrikhovka-i-graficheskie-diktanty',
  '/1-klass/chtenie/proza',
  '/1-klass/chtenie/stihi',
  '/1-klass/logika/analogii',
  '/1-klass/logika/orientaciya-v-prostranstve',
  '/1-klass/logika/zagadki',
  '/1-klass/okruzhayushchiy/zhivaya-i-nezhivaya-priroda',
  '/1-klass/okruzhayushchiy/pravila-bezopasnosti',
  // 2 класс
  '/2-klass/matematika/umnozhenie',
  '/2-klass/matematika/delenie',
  '/2-klass/matematika/dvuznachnye',
  '/2-klass/matematika/sravnenie-chisel',
  '/2-klass/russkiy/chasti-rechi',
  '/2-klass/russkiy/predlozhenie',
  '/2-klass/russkiy/koren-slova',
  '/2-klass/russkiy/bezudarnye-glasnye',
  '/2-klass/russkiy/shtrikhovka-i-graficheskie-diktanty',
  '/2-klass/okruzhayushchiy/priroda',
  '/2-klass/okruzhayushchiy/chelovek',
  '/2-klass/logika/logicheskie-zadachi',
  '/2-klass/logika/rebusy',
  '/2-klass/logika/zagadki',
  // 3 класс
  '/3-klass/matematika/trekhznachnye',
  '/3-klass/matematika/slozhnie-primery',
  '/3-klass/matematika/doli',
  '/3-klass/matematika/delenie-s-ostatkom',
  '/3-klass/russkiy/spryazhenie',
  '/3-klass/russkiy/slozhnie-predlozheniya',
  '/3-klass/russkiy/razbor-slova-po-sostavu',
  '/3-klass/angliyskiy/vocabulary',
  '/3-klass/angliyskiy/grammatika',
  '/3-klass/logika/kombinatorika',
  '/3-klass/logika/zadachi-na-vzveshivanie',
  // 4 класс
  '/4-klass/matematika/velikie-chisla',
  '/4-klass/matematika/desyatichnie-drobi',
  '/4-klass/matematika/geometriya',
  '/4-klass/matematika/poryadok-deystviy',
  '/4-klass/russkiy/stili-rechi',
  '/4-klass/russkiy/sintaksis',
  '/4-klass/russkiy/sklonenie-suschestvitelnykh',
  '/4-klass/literatura/klassika',
  '/4-klass/literatura/analiz-teksta',
  '/4-klass/logika/logicheskie-tablitsy',
  '/4-klass/logika/zadachi-na-perelivanie',
];
