export interface TrainerRef {
  slug: string;
  title: string;
  icon: string;
  desc: string;
}

export interface SegmentResources {
  vprKlass?: '3-klass' | '4-klass';
  mckoKlass?: '4-klass';
  posterKlass?: '2' | '3' | '4';
  trainers: TrainerRef[];
  generators?: TrainerRef[];
}

// Единый источник правды: какие реальные тренажёры, варианты ВПР и плакаты
// подходят каждому возрастному сегменту. Используется на страницах сегментов,
// чтобы не дублировать вручную и не создавать "мёртвые" ссылки на несуществующий контент.
export const SEGMENT_RESOURCES: Record<string, SegmentResources> = {
  '4-5-let': {
    trainers: [
      { slug: 'naydi-lishnee', title: 'Найди лишнее', icon: '🧩', desc: 'По форме, по цвету, по размеру' },
      { slug: 'naydi-paru', title: 'Найди пару', icon: '🃏', desc: 'Игра на память' },
      { slug: 'chto-izmenilos', title: 'Что изменилось?', icon: '👀', desc: 'Тренируем внимание' },
      { slug: 'sobery-po-poryadku', title: 'Собери по порядку', icon: '📏', desc: 'От маленькой к большой' },
      { slug: 'azbuky', title: 'Английский алфавит (игра)', icon: '🇬🇧', desc: 'A-Z с картинками' },
      { slug: 'numbers', title: 'Числа', icon: '🔢', desc: 'Учимся считать' },
      { slug: 'colors', title: 'Цвета', icon: '🌈', desc: 'Различаем цвета' },
      { slug: 'shapes-colors', title: 'Формы и цвета', icon: '🔺', desc: 'Фигуры и оттенки' },
      { slug: 'pogovorki', title: 'Поговорки и пословицы', icon: '💬', desc: 'Русский фольклор' },
      { slug: 'angliyskiy-alfavit', title: 'Английский алфавит (Alphabet)', icon: '🇬🇧', desc: 'Буквы, картинки и озвучка' },
      { slug: 'angliyskiy-schet', title: 'Счёт по-английски (Numbers)', icon: '🇬🇧', desc: 'Числа от 1 до 20 с озвучкой' },
      { slug: 'english-animals', title: 'Животные по-английски (Animals)', icon: '🐶', desc: 'С озвучкой' },
      { slug: 'english-colors', title: 'Цвета по-английски (Colors)', icon: '🌈', desc: 'С озвучкой' },
      { slug: 'english-shapes', title: 'Формы по-английски (Shapes)', icon: '🔺', desc: 'С озвучкой' },
      { slug: 'english-food', title: 'Еда по-английски (Food)', icon: '🍎', desc: 'С озвучкой' },
      { slug: 'english-family', title: 'Семья по-английски (Family)', icon: '👪', desc: 'С озвучкой' },
      { slug: 'english-clothes', title: 'Одежда по-английски (Clothes)', icon: '👕', desc: 'С озвучкой' },
      { slug: 'english-weather', title: 'Погода по-английски (Weather)', icon: '☀️', desc: 'С озвучкой' },
      { slug: 'english-school', title: 'Школьные принадлежности по-английски (School things)', icon: '🎒', desc: 'С озвучкой' },
    ],
  },
  '6-7-let': {
    trainers: [
      { slug: 'naydi-lishnee', title: 'Найди лишнее', icon: '🧩', desc: 'По форме, по цвету, по размеру' },
      { slug: 'naydi-paru', title: 'Найди пару', icon: '🃏', desc: 'Игра на память' },
      { slug: 'chto-izmenilos', title: 'Что изменилось?', icon: '👀', desc: 'Тренируем внимание' },
      { slug: 'sobery-po-poryadku', title: 'Собери по порядку', icon: '📏', desc: 'От маленькой к большой' },
      { slug: 'azbuky', title: 'Английский алфавит (игра)', icon: '🇬🇧', desc: 'A-Z с картинками' },
      { slug: 'numbers', title: 'Числа', icon: '🔢', desc: 'Счёт до 20' },
      { slug: 'colors', title: 'Цвета', icon: '🌈', desc: 'Различаем цвета' },
      { slug: 'shapes-colors', title: 'Формы и цвета', icon: '🔺', desc: 'Закрепляем формы' },
      { slug: 'pogovorki', title: 'Поговорки и пословицы', icon: '💬', desc: 'Русский фольклор' },
      { slug: 'angliyskiy-alfavit', title: 'Английский алфавит (Alphabet)', icon: '🇬🇧', desc: 'Буквы, картинки и озвучка' },
      { slug: 'angliyskiy-schet', title: 'Счёт по-английски (Numbers)', icon: '🇬🇧', desc: 'Числа от 1 до 20 с озвучкой' },
      { slug: 'english-words', title: 'Английские слова по темам (Words)', icon: '🇬🇧', desc: 'Разные темы с озвучкой' },
      { slug: 'english-animals', title: 'Животные по-английски (Animals)', icon: '🐶', desc: 'С озвучкой' },
      { slug: 'english-colors', title: 'Цвета по-английски (Colors)', icon: '🌈', desc: 'С озвучкой' },
      { slug: 'english-shapes', title: 'Формы по-английски (Shapes)', icon: '🔺', desc: 'С озвучкой' },
      { slug: 'english-food', title: 'Еда по-английски (Food)', icon: '🍎', desc: 'С озвучкой' },
      { slug: 'english-family', title: 'Семья по-английски (Family)', icon: '👪', desc: 'С озвучкой' },
      { slug: 'english-clothes', title: 'Одежда по-английски (Clothes)', icon: '👕', desc: 'С озвучкой' },
      { slug: 'english-weather', title: 'Погода по-английски (Weather)', icon: '☀️', desc: 'С озвучкой' },
      { slug: 'english-school', title: 'Школьные принадлежности по-английски (School things)', icon: '🎒', desc: 'С озвучкой' },
      { slug: 'mesyatsy-i-sezony', title: 'Месяцы и времена года', icon: '📅', desc: 'Определи время года по месяцу' },
      { slug: 'english-transport', title: 'Транспорт по-английски', icon: '🚗', desc: 'Игра «Найди пару»: слово и картинка' },
    ],
    generators: [
      { slug: 'anagrammy', title: 'Анаграммы', icon: '🔤', desc: 'Разгадай слово из перемешанных букв' },
      { slug: 'graficheskiy-diktant', title: 'Графический диктант', icon: '✏️', desc: 'Рисунок по клеточкам' },
      { slug: 'sostav-chisla', title: 'Состав числа', icon: '🏠', desc: '«Домики» для счёта' },
      { slug: 'schet-predmetov', title: 'Счёт предметов', icon: '🔢', desc: 'Считаем картинки' },
      { slug: 'propisi-ru', title: 'Прописи (рус.)', icon: '✍️', desc: 'Буквы русского алфавита' },
      { slug: 'naydi-i-poschitay', title: 'Найди и посчитай', icon: '👀', desc: 'Находилки: сколько каждого вида' },
      { slug: 'labirinty', title: 'Лабиринты', icon: '🌀', desc: '3 размера, от простого до сложного' },
      { slug: 'razdeli-na-gruppy', title: 'Раздели на группы', icon: '🧩', desc: 'Сортировка карточек по столбикам' },
      { slug: 'propisi-angliyskiy', title: 'Прописи (англ.)', icon: '✏️', desc: 'Английские буквы для тренировки почерка' },
    ],
  },
  '1-klass': {
    trainers: [
      { slug: 'azbuky', title: 'Английский алфавит (игра)', icon: '🇬🇧', desc: 'A-Z с картинками' },
      { slug: 'numbers', title: 'Числа', icon: '🔢', desc: 'Счёт и цифры' },
      { slug: 'colors', title: 'Цвета', icon: '🌈', desc: 'Различаем цвета' },
      { slug: 'shapes-colors', title: 'Формы и цвета', icon: '🔺', desc: 'Фигуры и оттенки' },
      { slug: 'pogovorki', title: 'Поговорки и пословицы', icon: '💬', desc: 'Русский фольклор' },
      { slug: 'angliyskiy-alfavit', title: 'Английский алфавит (Alphabet)', icon: '🇬🇧', desc: 'Буквы, картинки и озвучка' },
      { slug: 'angliyskiy-schet', title: 'Счёт по-английски (Numbers)', icon: '🇬🇧', desc: 'Числа от 1 до 20 с озвучкой' },
      { slug: 'english-words', title: 'Английские слова по темам (Words)', icon: '🇬🇧', desc: 'Разные темы с озвучкой' },
      { slug: 'english-animals', title: 'Животные по-английски (Animals)', icon: '🐶', desc: 'С озвучкой' },
      { slug: 'english-colors', title: 'Цвета по-английски (Colors)', icon: '🌈', desc: 'С озвучкой' },
      { slug: 'english-shapes', title: 'Формы по-английски (Shapes)', icon: '🔺', desc: 'С озвучкой' },
      { slug: 'english-food', title: 'Еда по-английски (Food)', icon: '🍎', desc: 'С озвучкой' },
      { slug: 'english-family', title: 'Семья по-английски (Family)', icon: '👪', desc: 'С озвучкой' },
      { slug: 'english-clothes', title: 'Одежда по-английски (Clothes)', icon: '👕', desc: 'С озвучкой' },
      { slug: 'english-weather', title: 'Погода по-английски (Weather)', icon: '☀️', desc: 'С озвучкой' },
      { slug: 'english-school', title: 'Школьные принадлежности по-английски (School things)', icon: '🎒', desc: 'С озвучкой' },
      { slug: 'english-transport', title: 'Транспорт по-английски', icon: '🚗', desc: 'Игра «Найди пару»: слово и картинка' },
      { slug: 'odushevlennye-neodushevlennye', title: 'Одушевлённые и неодушевлённые', icon: '🧍', desc: 'КТО? или ЧТО? — определи существительное' },
    ],
    generators: [
      { slug: 'filvordy', title: 'Филворды', icon: '🔍', desc: 'Найди слова в сетке букв' },
      { slug: 'krossvordy', title: 'Кроссворды', icon: '🔤', desc: 'Еда, животные, спорт и другие темы' },
      { slug: 'anagrammy', title: 'Анаграммы', icon: '🔤', desc: 'Разгадай слово из перемешанных букв' },
      { slug: 'primery', title: 'Примеры', icon: '📊', desc: 'Сложение и вычитание до 20' },
      { slug: 'propisi-ru', title: 'Прописи (рус.)', icon: '✍️', desc: 'Буквы русского алфавита' },
      { slug: 'zadachi', title: 'Задачи', icon: '🧩', desc: 'Простые текстовые задачи' },
      { slug: 'sostav-chisla', title: 'Состав числа', icon: '🏠', desc: '«Домики» для счёта' },
      { slug: 'graficheskiy-diktant', title: 'Графический диктант', icon: '✏️', desc: 'Рисунок по клеточкам' },
      { slug: 'matematicheskaya-raskraska', title: 'Математическая раскраска', icon: '🎨', desc: 'Реши пример — узнай цвет' },
      { slug: 'propisi-angliyskiy', title: 'Прописи (англ.)', icon: '✏️', desc: 'Английские буквы для тренировки почерка' },
      { slug: 'razdeli-na-gruppy', title: 'Раздели на группы', icon: '🧩', desc: 'Живая и неживая природа и другие темы' },
    ],
  },
  '2-klass': {
    posterKlass: '2',
    trainers: [
      { slug: 'tablitsa-umnozheniya', title: 'Таблица умножения', icon: '✖️', desc: '4 режима: таблица, тренировка, на время, множитель' },
      { slug: 'colors', title: 'Цвета', icon: '🌈', desc: 'Различаем цвета' },
      { slug: 'shapes-colors', title: 'Формы и цвета', icon: '🔺', desc: 'Фигуры и оттенки' },
      { slug: 'pogovorki', title: 'Поговорки и пословицы', icon: '💬', desc: 'Русский фольклор' },
      { slug: 'angliyskiy-alfavit', title: 'Английский алфавит (Alphabet)', icon: '🇬🇧', desc: 'Буквы, картинки и озвучка' },
      { slug: 'angliyskiy-schet', title: 'Счёт по-английски (Numbers)', icon: '🇬🇧', desc: 'Числа от 1 до 20 с озвучкой' },
      { slug: 'english-words', title: 'Английские слова по темам (Words)', icon: '🇬🇧', desc: 'Разные темы с озвучкой' },
      { slug: 'english-animals', title: 'Животные по-английски (Animals)', icon: '🐶', desc: 'С озвучкой' },
      { slug: 'english-colors', title: 'Цвета по-английски (Colors)', icon: '🌈', desc: 'С озвучкой' },
      { slug: 'english-shapes', title: 'Формы по-английски (Shapes)', icon: '🔺', desc: 'С озвучкой' },
      { slug: 'english-food', title: 'Еда по-английски (Food)', icon: '🍎', desc: 'С озвучкой' },
      { slug: 'english-family', title: 'Семья по-английски (Family)', icon: '👪', desc: 'С озвучкой' },
      { slug: 'english-clothes', title: 'Одежда по-английски (Clothes)', icon: '👕', desc: 'С озвучкой' },
      { slug: 'english-weather', title: 'Погода по-английски (Weather)', icon: '☀️', desc: 'С озвучкой' },
      { slug: 'english-school', title: 'Школьные принадлежности по-английски (School things)', icon: '🎒', desc: 'С озвучкой' },
      { slug: 'udarnyy-slog', title: 'Ударный слог', icon: '📢', desc: 'Нажми на слог, на который падает ударение' },
      { slug: 'odushevlennye-neodushevlennye', title: 'Одушевлённые и неодушевлённые', icon: '🧍', desc: 'КТО? или ЧТО? — определи существительное' },
      { slug: 'verno-ili-neverno-matematika', title: 'Верно или неверно: математика', icon: '✅', desc: 'Определи, верное это равенство или нет' },
      { slug: 'angliyskiy-artikli', title: 'Артикли a/an и множественное число', icon: '🔤', desc: 'Выбери верный артикль или форму слова' },
    ],
    generators: [
      { slug: 'filvordy', title: 'Филворды', icon: '🔍', desc: 'Найди слова в сетке букв' },
      { slug: 'krossvordy', title: 'Кроссворды', icon: '🔤', desc: 'Еда, животные, спорт и другие темы' },
      { slug: 'anagrammy', title: 'Анаграммы', icon: '🔤', desc: 'Разгадай слово из перемешанных букв' },
      { slug: 'primery', title: 'Примеры', icon: '📊', desc: 'Умножение, деление и другие режимы' },
      { slug: 'graficheskiy-diktant', title: 'Графический диктант', icon: '✏️', desc: 'Рисунок по клеточкам' },
      { slug: 'slovarnye-slova', title: 'Словарные слова', icon: '📖', desc: 'Непроверяемые слова по классам' },
      { slug: 'zadachi', title: 'Задачи', icon: '🧩', desc: 'Текстовые задачи с решением' },
      { slug: 'labirinty', title: 'Лабиринты', icon: '🌀', desc: '3 размера, для разного уровня' },
      { slug: 'matematicheskaya-raskraska', title: 'Математическая раскраска', icon: '🎨', desc: 'Реши пример — узнай цвет' },
      { slug: 'propisi-angliyskiy', title: 'Прописи (англ.)', icon: '✏️', desc: 'Английские буквы для тренировки почерка' },
      { slug: 'razdeli-na-gruppy', title: 'Раздели на группы', icon: '🧩', desc: 'Перелётные и зимующие птицы и другие темы' },
    ],
  },
  '3-klass': {
    vprKlass: '3-klass',
    posterKlass: '3',
    trainers: [
      { slug: 'tablitsa-umnozheniya', title: 'Таблица умножения', icon: '✖️', desc: '4 режима: таблица, тренировка, на время, множитель' },
      { slug: 'pristavki', title: 'Приставки', icon: '📝', desc: 'Приставки в словах' },
      { slug: 'english-words', title: 'Английские слова по темам (Words)', icon: '🇬🇧', desc: 'Разные темы с озвучкой' },
      { slug: 'irregular-verbs', title: 'Неправильные глаголы', icon: '🇬🇧', desc: 'Английская грамматика' },
      { slug: 'angliyskiy-schet', title: 'Счёт по-английски (Numbers)', icon: '🇬🇧', desc: 'Числа от 1 до 20 с озвучкой' },
      { slug: 'english-animals', title: 'Животные по-английски (Animals)', icon: '🐶', desc: 'С озвучкой' },
      { slug: 'english-colors', title: 'Цвета по-английски (Colors)', icon: '🌈', desc: 'С озвучкой' },
      { slug: 'english-shapes', title: 'Формы по-английски (Shapes)', icon: '🔺', desc: 'С озвучкой' },
      { slug: 'english-food', title: 'Еда по-английски (Food)', icon: '🍎', desc: 'С озвучкой' },
      { slug: 'english-family', title: 'Семья по-английски (Family)', icon: '👪', desc: 'С озвучкой' },
      { slug: 'english-clothes', title: 'Одежда по-английски (Clothes)', icon: '👕', desc: 'С озвучкой' },
      { slug: 'english-weather', title: 'Погода по-английски (Weather)', icon: '☀️', desc: 'С озвучкой' },
      { slug: 'english-school', title: 'Школьные принадлежности по-английски (School things)', icon: '🎒', desc: 'С озвучкой' },
      { slug: 'verno-ili-neverno-matematika', title: 'Верно или неверно: математика', icon: '✅', desc: 'Определи, верное это равенство или нет' },
      { slug: 'angliyskiy-artikli', title: 'Артикли a/an и множественное число', icon: '🔤', desc: 'Выбери верный артикль или форму слова' },
    ],
    generators: [
      { slug: 'filvordy', title: 'Филворды', icon: '🔍', desc: 'Найди слова в сетке букв' },
      { slug: 'krossvordy', title: 'Кроссворды', icon: '🔤', desc: 'Еда, животные, спорт и другие темы' },
      { slug: 'anagrammy', title: 'Анаграммы', icon: '🔤', desc: 'Разгадай слово из перемешанных букв' },
      { slug: 'primery', title: 'Примеры', icon: '📊', desc: 'В столбик и другие режимы' },
      { slug: 'diktanty', title: 'Диктанты', icon: '🎤', desc: 'Тексты для диктанта по классам' },
      { slug: 'slovarnye-slova', title: 'Словарные слова', icon: '📖', desc: 'Непроверяемые слова по классам' },
      { slug: 'propisi-angliyskiy', title: 'Прописи (англ.)', icon: '✏️', desc: 'Английские буквы для тренировки почерка' },
      { slug: 'sudoku', title: 'Судоку для детей', icon: '🎲', desc: '4×4, 6×6, 9×9 — по возрасту' },
    ],
  },
  '4-klass': {
    vprKlass: '4-klass',
    mckoKlass: '4-klass',
    posterKlass: '4',
    trainers: [
      { slug: 'tablitsa-umnozheniya', title: 'Таблица умножения', icon: '✖️', desc: '4 режима: таблица, тренировка, на время, множитель' },
      { slug: 'pristavki', title: 'Приставки', icon: '📝', desc: 'Русский язык' },
      { slug: 'pogovorki', title: 'Поговорки и пословицы', icon: '💬', desc: 'Литература и фольклор' },
      { slug: 'angliyskiy-schet', title: 'Счёт по-английски (Numbers)', icon: '🇬🇧', desc: 'Числа от 1 до 20 с озвучкой' },
      { slug: 'english-words', title: 'Английские слова по темам (Words)', icon: '🇬🇧', desc: 'Разные темы с озвучкой' },
      { slug: 'irregular-verbs', title: 'Неправильные глаголы', icon: '🇬🇧', desc: 'Таблица irregular verbs' },
      { slug: 'english-animals', title: 'Животные по-английски (Animals)', icon: '🐶', desc: 'С озвучкой' },
      { slug: 'english-colors', title: 'Цвета по-английски (Colors)', icon: '🌈', desc: 'С озвучкой' },
      { slug: 'english-shapes', title: 'Формы по-английски (Shapes)', icon: '🔺', desc: 'С озвучкой' },
      { slug: 'english-food', title: 'Еда по-английски (Food)', icon: '🍎', desc: 'С озвучкой' },
      { slug: 'english-family', title: 'Семья по-английски (Family)', icon: '👪', desc: 'С озвучкой' },
      { slug: 'english-clothes', title: 'Одежда по-английски (Clothes)', icon: '👕', desc: 'С озвучкой' },
      { slug: 'english-weather', title: 'Погода по-английски (Weather)', icon: '☀️', desc: 'С озвучкой' },
      { slug: 'english-school', title: 'Школьные принадлежности по-английски (School things)', icon: '🎒', desc: 'С озвучкой' },
      { slug: 'chasti-rechi-4klass', title: 'Части речи', icon: '📝', desc: 'Существительное, наречие, местоимение и другие' },
      { slug: 'angliyskiy-artikli', title: 'Артикли a/an и множественное число', icon: '🔤', desc: 'Выбери верный артикль или форму слова' },
    ],
    generators: [
      { slug: 'filvordy', title: 'Филворды', icon: '🔍', desc: 'Найди слова в сетке букв' },
      { slug: 'krossvordy', title: 'Кроссворды', icon: '🔤', desc: 'Еда, животные, спорт и другие темы' },
      { slug: 'anagrammy', title: 'Анаграммы', icon: '🔤', desc: 'Разгадай слово из перемешанных букв' },
      { slug: 'primery', title: 'Примеры в столбик', icon: '🧮', desc: 'Умножение и деление в столбик' },
      { slug: 'diktanty', title: 'Диктанты', icon: '🎤', desc: 'Тексты для диктанта по классам' },
      { slug: 'slovarnye-slova', title: 'Словарные слова', icon: '📖', desc: 'Непроверяемые слова по классам' },
      { slug: 'chitatelskiy-dnevnik', title: 'Читательский дневник', icon: '📖', desc: 'Обложка, страницы книг и сводная таблица' },
      { slug: 'sudoku', title: 'Судоку для детей', icon: '🎲', desc: '4×4, 6×6, 9×9 — по возрасту' },
    ],
  },
};
