export type VocabGrade = 1 | 2 | 3 | 4;

export interface VocabWord {
  word: string;
  // Индексы букв (0-based), которые нужно запомнить — непроверяемая
  // гласная/орфограмма. Именно эти позиции пропускаются в упражнении,
  // а не случайная буква.
  blanks: number[];
}

// Списки словарных слов по классам с разметкой «трудных» букв — позиция
// пропуска указана вручную для каждого слова, а не подобрана случайно.
export const VOCAB_WORDS: Record<VocabGrade, VocabWord[]> = {
  1: [
    { word: 'Яблоня', blanks: [0] },
    { word: 'Учительница', blanks: [4] },
    { word: 'Ученик', blanks: [2] },
    { word: 'Класс', blanks: [3, 4] },
    { word: 'Тетрадь', blanks: [1] },
    { word: 'Язык', blanks: [0] },
    { word: 'Россия', blanks: [1] },
    { word: 'Москва', blanks: [1] },
    { word: 'Русский', blanks: [2, 3] },
    { word: 'Фамилия', blanks: [1] },
    { word: 'Адрес', blanks: [3] },
    { word: 'Город', blanks: [3] },
    { word: 'Деревня', blanks: [1] },
    { word: 'Дорога', blanks: [1] },
    { word: 'Улица', blanks: [2] },
    { word: 'Родина', blanks: [3] },
    { word: 'Родной', blanks: [1] },
    { word: 'Площадь', blanks: [5] },
    { word: 'Кремль', blanks: [2] },
    { word: 'Здравствуйте', blanks: [4, 5, 6] },
    { word: 'Свидания', blanks: [2] },
    { word: 'Спасибо', blanks: [2] },
    { word: 'Пожалуйста', blanks: [1] },
    { word: 'Извините', blanks: [3] },
    { word: 'Ребята', blanks: [1] },
    { word: 'Собака', blanks: [1] },
    { word: 'Корова', blanks: [1] },
    { word: 'Кабан', blanks: [1] },
    { word: 'Заяц', blanks: [2] },
    { word: 'Щенок', blanks: [1] },
    { word: 'Медведь', blanks: [1] },
    { word: 'Ворона', blanks: [1] },
    { word: 'Сорока', blanks: [1] },
    { word: 'Воробей', blanks: [1, 3] },
    { word: 'Соловей', blanks: [1, 3] },
    { word: 'Петух', blanks: [1] },
    { word: 'Осина', blanks: [0] },
    { word: 'Берёза', blanks: [1] },
    { word: 'Тополь', blanks: [3] },
    { word: 'Рябина', blanks: [1] },
    { word: 'Огурец', blanks: [0] },
    { word: 'Помидор', blanks: [1] },
    { word: 'Морковь', blanks: [1] },
    { word: 'Капуста', blanks: [1] },
    { word: 'Картофель', blanks: [1, 6] },
    { word: 'Синица', blanks: [1] },
    { word: 'Картина', blanks: [1] },
    { word: 'Рисунок', blanks: [1] },
    { word: 'Товарищ', blanks: [1] },
    { word: 'Карандаш', blanks: [1, 3] },
    { word: 'Телёнок', blanks: [1] },
    { word: 'Овощи', blanks: [2] },
    { word: 'Щавель', blanks: [3] },
    { word: 'Огород', blanks: [0, 2] },
    { word: 'Месяц', blanks: [3] },
    { word: 'Январь', blanks: [0] },
    { word: 'Понедельник', blanks: [1, 3] },
    { word: 'Февраль', blanks: [1] },
    { word: 'Вторник', blanks: [0] },
    { word: 'Апрель', blanks: [0] },
    { word: 'Среда', blanks: [2] },
    { word: 'Июнь', blanks: [0] },
    { word: 'Четверг', blanks: [1, 6] },
    { word: 'Июль', blanks: [0] },
    { word: 'Пятница', blanks: [4] },
    { word: 'Сентябрь', blanks: [1] },
    { word: 'Суббота', blanks: [2, 3] },
    { word: 'Октябрь', blanks: [0] },
    { word: 'Воскресенье', blanks: [5] },
    { word: 'Ноябрь', blanks: [1] },
    { word: 'Ветер', blanks: [3] },
    { word: 'Декабрь', blanks: [1] },
    { word: 'Коньки', blanks: [1] },
    { word: 'Мороженое', blanks: [1] },
    { word: 'Телефон', blanks: [1, 3] },
    { word: 'Пальто', blanks: [1] },
  ],
  2: [
    { word: 'Мультфильм', blanks: [4] },
    { word: 'Кенгуру', blanks: [1] },
    { word: 'Ягода', blanks: [2] },
    { word: 'Метро', blanks: [1] },
    { word: 'Земляника', blanks: [1, 4] },
    { word: 'Меню', blanks: [1] },
    { word: 'Малина', blanks: [1] },
    { word: 'Желе', blanks: [1] },
    { word: 'Лето', blanks: [1] },
    { word: 'Барсук', blanks: [1] },
    { word: 'Снегирь', blanks: [2] },
    { word: 'Дятел', blanks: [3] },
    { word: 'Мороз', blanks: [1] },
    { word: 'Варежка', blanks: [4] },
    { word: 'Корзина', blanks: [1] },
    { word: 'Магазин', blanks: [1, 3] },
    { word: 'Лестница', blanks: [3] },
    { word: 'Праздник', blanks: [4] },
    { word: 'Сердце', blanks: [3] },
    { word: 'Чувствовать', blanks: [2] },
    { word: 'Автобус', blanks: [1] },
    { word: 'Вокзал', blanks: [2] },
    { word: 'Автомобиль', blanks: [1, 3, 5] },
    { word: 'Машина', blanks: [1] },
    { word: 'Транспорт', blanks: [6] },
    { word: 'Такси', blanks: [1] },
    { word: 'Билет', blanks: [1] },
    { word: 'Горох', blanks: [1] },
    { word: 'Берег', blanks: [3] },
    { word: 'Завод', blanks: [1] },
    { word: 'Пенал', blanks: [1] },
    { word: 'Ужин', blanks: [2] },
    { word: 'Иней', blanks: [2] },
    { word: 'Хорошо', blanks: [1, 3] },
    { word: 'Берлога', blanks: [1] },
    { word: 'Облако', blanks: [3] },
    { word: 'Сарафан', blanks: [1, 3] },
    { word: 'Пирог', blanks: [1] },
    { word: 'Конфета', blanks: [1] },
    { word: 'Шоколад', blanks: [1, 3, 6] },
    { word: 'Чёрный', blanks: [1] },
    { word: 'Жёлтый', blanks: [1] },
    { word: 'Оранжевый', blanks: [0, 5] },
    { word: 'Коричневый', blanks: [1] },
    { word: 'Комната', blanks: [4] },
    { word: 'Сейчас', blanks: [1] },
    { word: 'Быстро', blanks: [5] },
    { word: 'Вдруг', blanks: [4] },
    { word: 'Вчера', blanks: [2] },
    { word: 'Завтра', blanks: [5] },
    { word: 'Однажды', blanks: [0] },
    { word: 'Сегодня', blanks: [2] },
    { word: 'Скоро', blanks: [4] },
    { word: 'Диван', blanks: [1] },
    { word: 'Коридор', blanks: [1] },
    { word: 'Квартира', blanks: [2] },
    { word: 'Здание', blanks: [0] },
    { word: 'Посуда', blanks: [1] },
    { word: 'Тарелка', blanks: [1] },
    { word: 'Стакан', blanks: [2] },
    { word: 'Молоко', blanks: [1] },
    { word: 'Обед', blanks: [0] },
    { word: 'Кастрюля', blanks: [1] },
    { word: 'Завтрак', blanks: [2] },
    { word: 'Столица', blanks: [2] },
    { word: 'Платок', blanks: [2] },
    { word: 'Лопата', blanks: [1] },
    { word: 'Одежда', blanks: [0] },
    { word: 'Поляна', blanks: [1] },
    { word: 'Дежурный', blanks: [1] },
    { word: 'Телевизор', blanks: [1, 3, 7] },
    { word: 'Народ', blanks: [4] },
    { word: 'Отец', blanks: [0] },
    { word: 'Компьютер', blanks: [1, 7] },
  ],
  3: [
    { word: 'Космонавт', blanks: [4, 7] },
    { word: 'Космос', blanks: [4] },
    { word: 'Герой', blanks: [1] },
    { word: 'Планета', blanks: [2] },
    { word: 'Мечта', blanks: [1] },
    { word: 'Дневник', blanks: [2] },
    { word: 'Сосед', blanks: [1] },
    { word: 'Орёл', blanks: [0] },
    { word: 'Лагерь', blanks: [3] },
    { word: 'Болото', blanks: [1] },
    { word: 'Ракета', blanks: [1] },
    { word: 'Остров', blanks: [4] },
    { word: 'Свёкла', blanks: [2] },
    { word: 'Квартал', blanks: [2] },
    { word: 'Песок', blanks: [1] },
    { word: 'Интересный', blanks: [3] },
    { word: 'Гигант', blanks: [1] },
    { word: 'Привет', blanks: [2] },
    { word: 'Шелест', blanks: [3] },
    { word: 'Шофёр', blanks: [1] },
    { word: 'Газета', blanks: [1] },
    { word: 'Трамвай', blanks: [2] },
    { word: 'Один', blanks: [0] },
    { word: 'Инженер', blanks: [3] },
    { word: 'Орех', blanks: [0] },
    { word: 'Аптека', blanks: [0] },
    { word: 'Багаж', blanks: [1] },
    { word: 'Беседа', blanks: [1] },
    { word: 'Библиотека', blanks: [1, 5] },
    { word: 'Ботинки', blanks: [1] },
    { word: 'Вагон', blanks: [1] },
    { word: 'Галерея', blanks: [1, 3] },
    { word: 'Календарь', blanks: [1, 3] },
    { word: 'Костёр', blanks: [1] },
    { word: 'Костюм', blanks: [1] },
    { word: 'Овёс', blanks: [0] },
    { word: 'Молоток', blanks: [1, 3] },
    { word: 'Океан', blanks: [0, 2] },
    { word: 'Везде', blanks: [1] },
    { word: 'Вместе', blanks: [5] },
    { word: 'Вокруг', blanks: [1, 5] },
    { word: 'Восток', blanks: [1] },
    { word: 'Впереди', blanks: [2, 4] },
    { word: 'Запад', blanks: [3] },
    { word: 'Здесь', blanks: [0] },
    { word: 'Когда', blanks: [1] },
    { word: 'Конечно', blanks: [1, 6] },
    { word: 'Лучше', blanks: [4] },
    { word: 'Медленно', blanks: [4] },
    { word: 'Назад', blanks: [1] },
    { word: 'Очень', blanks: [2] },
    { word: 'Потом', blanks: [1] },
    { word: 'Север', blanks: [3] },
    { word: 'Теперь', blanks: [1] },
    { word: 'Это', blanks: [0] },
    { word: 'Ещё', blanks: [0] },
    { word: 'Оттуда', blanks: [0] },
    { word: 'Ландыш', blanks: [4] },
    { word: 'Ромашка', blanks: [1] },
    { word: 'Гвоздика', blanks: [2] },
    { word: 'Колокольчик', blanks: [1, 3] },
    { word: 'Незабудка', blanks: [1, 3, 6] },
    { word: 'Пион', blanks: [1] },
    { word: 'Фиалка', blanks: [1] },
    { word: 'Подсолнух', blanks: [1] },
    { word: 'Орхидея', blanks: [0, 3] },
    { word: 'Одуванчик', blanks: [0] },
    { word: 'Нарцисс', blanks: [1, 4] },
    { word: 'Полынь', blanks: [1] },
  ],
  4: [
    { word: 'Прекрасный', blanks: [2] },
    { word: 'Библиотека', blanks: [4] },
    { word: 'Библиотекарь', blanks: [4] },
    { word: 'Шофёр', blanks: [1] },
    { word: 'Ещё', blanks: [0] },
    { word: 'Корабль', blanks: [1] },
    { word: 'Костюм', blanks: [1] },
    { word: 'Железо', blanks: [1] },
    { word: 'Вокзал', blanks: [2] },
    { word: 'Пассажир', blanks: [2, 3] },
    { word: 'Пассажирский', blanks: [2, 3] },
    { word: 'Билет', blanks: [1] },
    { word: 'Двенадцать', blanks: [2] },
    { word: 'Впереди', blanks: [2] },
    { word: 'Медленно', blanks: [4] },
    { word: 'Здесь', blanks: [0] },
    { word: 'Вчера', blanks: [2] },
    { word: 'Теперь', blanks: [1] },
    { word: 'Завтра', blanks: [5] },
    { word: 'Телефон', blanks: [1] },
    { word: 'Телепередача', blanks: [1] },
    { word: 'Аллея', blanks: [2] },
    { word: 'Беседа', blanks: [1] },
    { word: 'Беседовать', blanks: [1] },
    { word: 'Агроном', blanks: [0] },
    { word: 'Пейзаж', blanks: [1] },
    { word: 'Инженер', blanks: [0] },
    { word: 'Хлебороб', blanks: [4] },
    { word: 'Овца', blanks: [0] },
    { word: 'Сегодня', blanks: [2] },
    { word: 'Костёр', blanks: [1] },
    { word: 'Портрет', blanks: [1] },
    { word: 'Путешествие', blanks: [3] },
    { word: 'Путешественник', blanks: [3] },
    { word: 'Директор', blanks: [1] },
    { word: 'Килограмм', blanks: [3] },
    { word: 'Грамм', blanks: [3] },
    { word: 'Газета', blanks: [1] },
  ],
};

export interface VocabExerciseItem {
  word: string;
  display: string;
}

function makeBlankDisplay(word: string, blanks: number[]): string {
  const chars = word.split('');
  for (const idx of blanks) {
    if (idx >= 0 && idx < chars.length) chars[idx] = '_';
  }
  return chars.join('');
}

export function generateVocabExercise(grade: VocabGrade, count: number): VocabExerciseItem[] {
  const pool = VOCAB_WORDS[grade];
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  const picked = shuffled.slice(0, Math.min(count, shuffled.length));
  return picked.map(({ word, blanks }) => ({ word, display: makeBlankDisplay(word, blanks) }));
}

export function pickVocabList(grade: VocabGrade, count: number): string[] {
  const pool = VOCAB_WORDS[grade];
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length)).map((w) => w.word);
}
